= 福州话罗马字简史

**福州话罗马字** (平话字： **Bàng-uâ-cê**，英语: **Foochow Romanized**)，也称平话字 是由来福州的西方传教士发明一种拉丁化方案。

[WARNING]
====
这里“平话字” 和19-20世纪初福州百姓所称的“平话字”不同。当时所称的“平话字”<<1>>是相对于文言文而言，用于记录口语的“白话文”，其中含有以近音代替的字或训读字，可以称作“方言俗字。 但是，当时这种民间白话文的流行，也是促使传教士用福州话翻译《圣经》的原因之一。
====

在最早的一篇传教士所写的福州话研究 **The Chinese Language Spoken at Fuh Chau** (The Methodist Review, 1856) 中，作者 **M.C. White** 基于 福州话传统韵书 《戚林八音》， 借鉴 **William Jones 系统** (一种用于描述？？语言的拉丁化方案)，创造了一套福州话罗马化的系统。 <<2>>

后来的传教士，在这套系统的基础上，作出一些改进，比如：

 - 用 b, d, g 代替 p', t', k'
 - 将部分元音的**“屎点”**移动到下方，从而避免和声调符号冲突

与福州话罗马字同时期的其他书写系统，还包括力捷三的《闽腔快字》。但是后者的流行度？

== 使用情况

平话字一直以来主要在教会使用，但并没有在广大老百姓中大面积普及。[^Source?]

在教会中， 《圣经》（包括新约、旧约）等，都以平话字翻译为福州话。<<3>> <<4>> 其他如《赞美诗集》等大量传教作品，也使用了平话字。

一些教会学校，如福州的陶淑女中和格致书院[^Source?]，也将平话字列入课程。

[TIP]
.既然平话字不曾普及，我们为何还要教学？ 
====
因为爱（误）。 因为是最系统使用过的罗马字方案？
====

由于旧时普通百姓汉字识字率低，平话字成为信徒书写母语的首选。[^（此段抄自维基百科）]

最近一个多世纪以来，随着**国语运动**、**推广普通话**等，另一方面，汉字的识字率渐渐提高，平话字渐渐被人所遗忘。

不过，目前，平话字是**维基媒体基金会**旗下的[**维基百科（闽东语版）**](https://cdo.wikipedia.org)所用的文字之一（和汉字并用）。

## 参考文献
[bibliography]
- [[[1]]] 陈泽平. (2010). _19世纪以来的福州方言_. 福州: 福建人民出版社. pp. 19.

- [[[2]]] [《在福州所说的汉语》](https://en.wikisource.org/wiki/The_Chinese_Language_Spoken_at_Fuh_Chau)

- [[[3]]] [《聖經新約》(SÉNG-GĬNG SĬNG-IÓK) 平話字版 - Cornell University](http://ebooks.library.cornell.edu/cgi/t/text/text-idx?c=cdl;cc=cdl;view=toc;subview=short;idno=cdl180)

- [[[4]]] [《聖經舊約》(SÉNG-GĬNG GÔ-IÓK) 平话字版 - Cornell University](http://ebooks.library.cornell.edu/cgi/t/text/text-idx?c=cdl;cc=cdl;view=toc;subview=short;idno=cdl181)