= 福州话罗马字简史

**福州话罗马字** (**Foochow Romanized**)，也称**平话字**是由来福州的西方传教士发明一种福州话拉丁化方案。

[TIP]
.此平话字非彼平话字
====
在有的文献中，你可能会发现“平话字”一词有另外的含义。

我们这里说的**福州话罗马字（平话字）**与 19 世纪末到 20 世纪初福州百姓所称的“平话字”不同。


当时所称的“平话字”<<1>>是相对于文言文而言的。用于记录口语的“白话文”，其中含有以近音代替的字或训读字，可以称作“方言俗字”。“平话”的字面意思就是“平常说的话”，因此老百姓以此自称自己讲的话和写的俗字。^需要证据^ 当时这种民间白话文的流行，也是促使传教士用福州话翻译《圣经》的原因之一。

其实，传教士们只称呼这种文字为 **Foochow Romanized**。**福州话罗马字**抑或**平话字**都是今人所起的名字。
====

== 创造
在最早的一篇传教士所写的福州话研究 **The Chinese Language Spoken at Fuh Chau** (The Methodist Review, 1856) 中，作者 **M.C. White** 基于福州话传统韵书——《戚林八音》， 借鉴 **William Jones 系统** (一种用于描述？？语言的拉丁化方案)，创造了一套福州话罗马化的系统。 <<2>>

《榕腔初学撮要》(Manual of the Foochow Dialect)

////
后来的传教士，在这套系统的基础上，作出一些改进，比如：

* 用 b, d, g 代替 p', t', k'
* 将部分元音的**变音点**移动到下方，从而避免和声调符号冲突
////

[TIP]
.福州话的其他书写系统
====
与福州话罗马字同时期的其他书写系统，还包括:

* 《闽腔快字》力捷三,???。但是流行度？

====

== 推广

教会一直是福州话罗马字的主要推动者。

在教会中， 《圣经》（包括新约、旧约）等，都以平话字翻译为福州话。
footnote:[http://ebooks.library.cornell.edu/cgi/t/text/text-idx?c=cdl;cc=cdl;view=toc;subview=short;idno=cdl180[《聖經新約》(SÉNG-GĬNG SĬNG-IÓK)] 平話字版 - Cornell University
]
footnote:[http://ebooks.library.cornell.edu/cgi/t/text/text-idx?c=cdl;cc=cdl;view=toc;subview=short;idno=cdl181[《聖經舊約》(SÉNG-GĬNG GÔ-IÓK)] 平话字版 - Cornell University]其他如《赞美诗集》等大量传教作品，也使用了平话字。

一些教会学校，如福州的陶淑女中和格致书院^Source?^，也将平话字列入课程。



[quote, 《中华教会年鉴》 1918]
.1917年，福州的美以美会大会通过决议：<<3>>
____
一、每一个会堂的传教士，必须立刻为他本堂的会友设立一个罗马字班，每星期至少上课一次。

二、每一个教区，应该为本区的工作人员每年举行一次规定的罗马字研究，指导他们怎样教民众学习罗马字。

三、尽力设法使罗马字书籍能便宜于目前的价格。

四、每一个传教士应在次年大会中报告本教区或本会堂学习罗马字的人数。
____

由于旧时普通百姓汉字识字率低，平话字成为信徒书写母语的首选。


== 现状
福州话罗马字一直以来主要在教会使用，但并没有在广大老百姓中大面积普及。^Source?^
最近一个多世纪以来，随着**国语运动**、**推广普通话**等，另一方面，汉字的识字率渐渐提高，平话字渐渐被人所遗忘。

不过，目前，福州话罗马字是 **维基媒体基金会** 旗下的 https://cdo.wikipedia.org[**维基百科（闽东语版）**] 所用的文字之一（和汉字并用）。
[TIP]
.既然福州话罗马字不曾普及，我们为何还要教学？
====
* 罗马字是福州话除了汉字之外，拥有最多文献的书写系统。读懂罗马字，就能读懂不少旧文献。
* 比起切韵，福州话罗马字更易掌握。^证据？^
* 比起国际音标，或是其它用于_记音_的拼音系统，~福州话罗马字并不遵循~

====


## 参考文献
[bibliography]
- [[[1]]] 陈泽平. (2010). _19世纪以来的福州方言_. 福州: 福建人民出版社. pp. 19.

- [[[2]]] https://en.wikisource.org/wiki/The_Chinese_Language_Spoken_at_Fuh_Chau[《在福州所说的汉语》]

- [[[3]]] 赵广军. (2012). 方言、宗教传播与文字革新. _井冈山大学学报(社会科学版)_.
